import { NextResponse } from 'next/server'
import { createClient, createServiceClient } from '@/lib/supabase/server'
import { sendSMS } from '@/lib/twilio'
import { sendEmail } from '@/lib/resend-client'
import { applyTemplate, DEFAULT_SMS_TEMPLATE, DEFAULT_EMAIL_SUBJECT, DEFAULT_EMAIL_BODY } from '@/lib/templates'

export async function POST(request: Request) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: profile } = await supabase
    .from('profiles')
    .select('*, businesses(*)')
    .eq('id', user.id)
    .single()

  if (!profile) return NextResponse.json({ error: 'Profile not found' }, { status: 404 })

  const business = profile.businesses!
  const { customerId, channel } = await request.json()

  // Enforce plan limit
  if (
    business.monthly_request_limit !== -1 &&
    business.requests_used_this_period >= business.monthly_request_limit
  ) {
    return NextResponse.json(
      { error: 'Monthly request limit reached. Please upgrade your plan.' },
      { status: 402 }
    )
  }

  const { data: customer } = await supabase
    .from('customers')
    .select('*')
    .eq('id', customerId)
    .eq('business_id', business.id)
    .single()

  if (!customer) return NextResponse.json({ error: 'Customer not found' }, { status: 404 })

  const serviceSupabase = await createServiceClient()

  // Insert request row (token generated by DB default)
  const { data: reviewRequest, error: insertErr } = await serviceSupabase
    .from('review_requests')
    .insert({
      business_id: business.id,
      customer_id: customerId,
      channel,
      sent_at: new Date().toISOString(),
      status: 'sent',
    })
    .select()
    .single()

  if (insertErr || !reviewRequest) {
    return NextResponse.json({ error: 'Failed to create review request' }, { status: 500 })
  }

  const link = `${process.env.NEXT_PUBLIC_APP_URL}/r/${reviewRequest.token}`
  const vars = {
    customer_name: customer.name,
    business_name: business.name,
    link,
  }

  const errors: string[] = []

  // Send SMS
  if ((channel === 'sms' || channel === 'both') && customer.phone) {
    const { data: optOut } = await serviceSupabase
      .from('opt_outs')
      .select('id')
      .eq('business_id', business.id)
      .eq('phone', customer.phone)
      .maybeSingle()

    if (optOut) {
      errors.push('Customer has opted out of SMS.')
    } else {
      try {
        const body = applyTemplate(business.sms_template ?? DEFAULT_SMS_TEMPLATE, vars)
        await sendSMS(customer.phone, body)
      } catch (err) {
        console.error('SMS send error:', err)
        errors.push('SMS failed to send.')
      }
    }
  }

  // Send email
  if ((channel === 'email' || channel === 'both') && customer.email) {
    try {
      const subject = applyTemplate(business.email_template_subject ?? DEFAULT_EMAIL_SUBJECT, vars)
      const html = applyTemplate(business.email_template_body ?? DEFAULT_EMAIL_BODY, vars)
      await sendEmail({ to: customer.email, subject, html })
    } catch (err) {
      console.error('Email send error:', err)
      errors.push('Email failed to send.')
    }
  }

  // Increment usage counter
  await serviceSupabase
    .from('businesses')
    .update({ requests_used_this_period: business.requests_used_this_period + 1 })
    .eq('id', business.id)

  if (errors.length && errors.length === (channel === 'both' ? 2 : 1)) {
    return NextResponse.json({ error: errors.join(' ') }, { status: 500 })
  }

  return NextResponse.json({ success: true, token: reviewRequest.token, warnings: errors })
}
